install:
  - appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  - appveyor DownloadFile https://github.com/nats-io/nats-streaming-server/releases/download/v0.12.0/nats-streaming-server-v0.12.0-windows-amd64.zip
  - appveyor DownloadFile https://github.com/nats-io/gnatsd/releases/download/v1.4.1/gnatsd-v1.4.1-windows-amd64.zip
  - 7z e nats-streaming-server-v0.12.0-windows-amd64.zip nats-streaming-server.exe -r -oc:\projects\nss\build
  - 7z e  gnatsd-v1.4.1-windows-amd64.zip gnatsd.exe -r -oc:\projects\nss\build
  - cmd: set PATH=%PATH%;C:\projects\nss\build
  - cmd: gnatsd -version
  - cmd: nats-streaming-server.exe -version

# to add several configurations to build matrix:
configuration:
  - Release

environment:
  matrix:
    - arch_name: core
    - arch_name: net45

# to run your custom scripts instead of automatic MSBuild
build_script:
  - cmd: appveyor\bld%arch_name%.bat

test_script:
  - cmd: appveyor\test%arch_name%.bat

notifications:
  - provider: GitHubPullRequest
    auth_token:
      secure: XI9j+cGG2z/YLFNk+KCnLQ==
