name: $(SemVer)

variables:
  SemVer: $[ variables['Build.SourceBranchName'] ]
  InfoVer: $(Build.SourceVersion)

trigger:
  batch: true
  branches:
    include:
    - refs/tags/*

pr: none

pool:
  vmImage: windows-2019

stages:
- template: az-templates/stage-build.yml
- template: az-templates/stage-deploy.yml
